---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	extract_query(extract_query)
	assess_feasibility(assess_feasibility)
	case_classification(case_classification)
	plan_structured_search(plan_structured_search)
	schedule_tool(schedule_tool)
	consume_tool(consume_tool)
	tool_executor(tool_executor)
	generate(generate)
	check_hallucination(check_hallucination)
	rewrite(rewrite)
	basic_generate(basic_generate)
	format_answer(format_answer)
	summarize_messages(summarize_messages)
	truncate_messages(truncate_messages)
	__end__([<p>__end__</p>]):::last
	__start__ --> extract_query;
	assess_feasibility -. &nbsp;general_answer&nbsp; .-> basic_generate;
	assess_feasibility -. &nbsp;rag_answer&nbsp; .-> case_classification;
	basic_generate --> format_answer;
	case_classification --> plan_structured_search;
	check_hallucination -. &nbsp;not hallucinated&nbsp; .-> format_answer;
	check_hallucination -. &nbsp;hallucinated&nbsp; .-> rewrite;
	consume_tool -. &nbsp;continue&nbsp; .-> generate;
	consume_tool -. &nbsp;more_tools&nbsp; .-> schedule_tool;
	extract_query --> assess_feasibility;
	format_answer --> summarize_messages;
	generate --> check_hallucination;
	plan_structured_search --> schedule_tool;
	rewrite --> schedule_tool;
	schedule_tool -. &nbsp;resume&nbsp; .-> generate;
	schedule_tool -. &nbsp;tools&nbsp; .-> tool_executor;
	summarize_messages --> truncate_messages;
	tool_executor --> consume_tool;
	truncate_messages --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
