---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	extract_query(extract_query)
	case_classification(case_classification)
	retrieve(retrieve)
	generate(generate)
	check_hallucination(check_hallucination)
	rewrite(rewrite)
	basic_generate(basic_generate)
	format_answer(format_answer)
	summarize_messages(summarize_messages)
	truncate_messages(truncate_messages)
	__end__([<p>__end__</p>]):::last
	__start__ --> extract_query;
	basic_generate --> format_answer;
	case_classification --> retrieve;
	check_hallucination -. &nbsp;not hallucinated&nbsp; .-> format_answer;
	check_hallucination -. &nbsp;hallucinated&nbsp; .-> rewrite;
	extract_query -. &nbsp;general_answer&nbsp; .-> basic_generate;
	extract_query -. &nbsp;rag_answer&nbsp; .-> case_classification;
	format_answer --> summarize_messages;
	generate --> check_hallucination;
	retrieve --> generate;
	rewrite --> retrieve;
	summarize_messages --> truncate_messages;
	truncate_messages --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
